apiVersion: apps/v1
kind: Deployment
metadata:
  name: agents
spec:
  replicas: 2
  selector:
    matchLabels:
      app: agents
  template:
    metadata:
      labels:
        app: agents
    spec:
      containers:
      - name: agents
        image: your-registry/agents:latest
        envFrom:
        - configMapRef:
            name: complaint-analysis-config
        - secretRef:
            name: complaint-analysis-secrets
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
      volumes:
      - name: google-cloud-key
        secret:
          secretName: complaint-analysis-secrets
          items:
          - key: GOOGLE_APPLICATION_CREDENTIALS
            path: key.json