apiVersion: v1
kind: ConfigMap
metadata:
  name: complaint-analysis-config
data:
  postgres-host: "postgres-service"
  elasticsearch-url: "http://elasticsearch-service:9200"
  redis-host: "redis-service"
  celery-broker-url: "redis://redis-service:6379/0"